---
# This file includes all Tutor setting defaults. Settings that do not have a
# default value, such as passwords, should be stored in base.yml.
# This must be defined early
CADDY_HTTP_PORT: 80
CMS_AUTOSCALING: false
CMS_AVG_CPU: 75
CMS_AVG_MEMORY: 1792Mi
CMS_CPU_LIMIT: 2
CMS_HOST: "studio.{{ LMS_HOST }}"
CMS_MAX_REPLICAS: 2
CMS_MEMORY_LIMIT: 4Gi
CMS_MEMORY_REQUEST: 2Gi
CMS_MIN_REPLICAS: 1
CMS_OAUTH2_KEY_SSO_DEV: "cms-sso-dev"
CMS_OAUTH2_KEY_SSO: "cms-sso"
CMS_WORKER_AUTOSCALING: false
CMS_WORKER_AVG_CPU: 75
CMS_WORKER_AVG_MEMORY: 1792Mi
CMS_WORKER_CPU_LIMIT: 2
CMS_WORKER_MAX_REPLICAS: 4
CMS_WORKER_MEMORY_LIMIT: 2Gi
CMS_WORKER_MIN_REPLICAS: 1
CONTACT_EMAIL: "contact@{{ LMS_HOST }}"
DEV_PROJECT_NAME: "{{ TUTOR_APP }}_dev"
DOCKER_COMPOSE_VERSION: "3.7"
DOCKER_IMAGE_CADDY: "docker.io/caddy:2.4.6"
DOCKER_IMAGE_ELASTICSEARCH: "docker.io/elasticsearch:7.10.1"
DOCKER_IMAGE_MONGODB: "docker.io/mongo:4.2.17"
DOCKER_IMAGE_MYSQL: "docker.io/mysql:5.7.35"
DOCKER_IMAGE_OPENEDX_DEV: "openedx-dev"
DOCKER_IMAGE_OPENEDX: "{{ DOCKER_REGISTRY }}overhangio/openedx:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_PERMISSIONS: "{{ DOCKER_REGISTRY }}overhangio/openedx-permissions:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_REDIS: "docker.io/redis:6.2.6"
DOCKER_IMAGE_SMTP: "docker.io/devture/exim-relay:4.95-r0-2"
DOCKER_REGISTRY: "docker.io/"
EDX_PLATFORM_REPOSITORY: "https://github.com/openedx/edx-platform.git"
EDX_PLATFORM_VERSION: "{{ OPENEDX_COMMON_VERSION }}"
ELASTICSEARCH_HEAP_SIZE: 1g
ELASTICSEARCH_HOST: "elasticsearch"
ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_SCHEME: "http"
ENABLE_HTTPS: false
ENABLE_WEB_PROXY: true
JWT_COMMON_AUDIENCE: "openedx"
JWT_COMMON_ISSUER: "{% if ENABLE_HTTPS %}https{% else %}http{% endif %}://{{ LMS_HOST }}/oauth2"
JWT_COMMON_SECRET_KEY: "{{ OPENEDX_SECRET_KEY }}"
K8S_NAMESPACE: "openedx"
LANGUAGE_CODE: "en"
LMS_AUTOSCALING: false
LMS_AVG_CPU: 75
LMS_AVG_MEMORY: 1792Mi
LMS_CPU_LIMIT: 2
LMS_HOST: "www.myopenedx.com"
LMS_MAX_REPLICAS: 2
LMS_MEMORY_LIMIT: 4Gi
LMS_MEMORY_REQUEST: 2Gi
LMS_MIN_REPLICAS: 1
LMS_WORKER_AUTOSCALING: false
LMS_WORKER_AVG_CPU: 75
LMS_WORKER_AVG_MEMORY: 1792Mi
LMS_WORKER_CPU_LIMIT: 2
LMS_WORKER_MAX_REPLICAS: 4
LMS_WORKER_MEMORY_LIMIT: 2Gi
LMS_WORKER_MIN_REPLICAS: 1
LOCAL_PROJECT_NAME: "{{ TUTOR_APP }}_local"
MONGODB_DATABASE: "openedx"
MONGODB_HOST: "mongodb"
MONGODB_PASSWORD: ""
MONGODB_PORT: 27017
MONGODB_USERNAME: ""
MYSQL_HOST: "mysql"
MYSQL_PORT: 3306
MYSQL_ROOT_USERNAME: "root"
NPM_REGISTRY: "https://registry.npmjs.org/"
OPENEDX_AWS_ACCESS_KEY: ""
OPENEDX_AWS_SECRET_ACCESS_KEY: ""
OPENEDX_CACHE_REDIS_DB: 1
OPENEDX_CELERY_REDIS_DB: 0
OPENEDX_CMS_UWSGI_WORKERS: 2
OPENEDX_LMS_UWSGI_WORKERS: 2
OPENEDX_MYSQL_DATABASE: "openedx"
OPENEDX_CSMH_MYSQL_DATABASE: "{{ OPENEDX_MYSQL_DATABASE }}_csmh"
OPENEDX_MYSQL_USERNAME: "openedx"
OPENEDX_COMMON_VERSION: "open-release/nutmeg.1"
OPENEDX_EXTRA_PIP_REQUIREMENTS:
  - "openedx-scorm-xblock<14.0.0,>=13.0.0"
OPENEDX_LMS_UWSGI_WORKERS: 2
OPENEDX_MYSQL_DATABASE: "openedx"
OPENEDX_MYSQL_USERNAME: "openedx"
PLATFORM_NAME: "My Open edX"
PREVIEW_LMS_HOST: "preview.{{ LMS_HOST }}"
REDIS_HOST: "redis"
REDIS_PASSWORD: ""
REDIS_PORT: 6379
REDIS_USERNAME: ""
RUN_CMS: true
RUN_ELASTICSEARCH: true
RUN_LMS: true
RUN_MONGODB: true
RUN_MYSQL: true
RUN_REDIS: true
RUN_SMTP: true
SMTP_HOST: "smtp"
SMTP_PASSWORD: ""
SMTP_PORT: 8025
SMTP_USE_SSL: false
SMTP_USE_TLS: false
SMTP_USERNAME: ""
